spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/authserver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5