polar:
  greeting: "Welcome to the catalog from the config server"
spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5